from typing import Any, Callable
from .components import Component
GetComponent: Any
def CreateComponent[T: Component](
    cls: type[T],
    *,
    parent: Component = ...,
    **kwargs,
) -> T: ...
def web_get(url: str, callback: Callable[[int, str], Any] = ..., headers: Any = ...) -> None: ...
def web_delete(url: str, callback: Callable[[int, str], Any] = ..., headers: Any = ...) -> None: ...
def web_patch(url: str, callback: Callable[[int, str], Any] = ..., data: str = ..., headers: Any = ...) -> None: ...
def web_post(url: str, callback: Callable[[int, str], Any] = ..., data: str = ..., headers: Any = ...) -> None: ...
def web_put(url: str, callback: Callable[[int, str], Any] = ..., data: str = ..., headers: Any = ...) -> None: ...
def obfs_text(text: str) -> str: ...
def get_compile_env(name: str) -> str: ...
class CloseScreen(Exception): ...
class CloseApplication(Exception): ...
